# Generated by Django 3.2b1 on 2021-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='productionCountry',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
