# Generated by Django 3.2b1 on 2021-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_tvshow_productioncountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='blabla',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
