# Generated by Django 3.2b1 on 2021-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_season_blabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='blabla',
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.TimeField(default='00:44'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='episodeNumber',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='releaseDate',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='seasonNumber',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
