# Generated by Django 3.2b1 on 2021-02-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_auto_20210228_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episodeNumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='seasonNumber',
            new_name='number',
        ),
    ]
