# Generated by Django 3.2b1 on 2021-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0005_auto_20210228_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(),
        ),
    ]
