# Generated by Django 3.2b1 on 2021-03-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0006_alter_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='videoUrl',
            field=models.CharField(default='a', max_length=2500),
            preserve_default=False,
        ),
    ]
